In [ ]:
import os
os.chdir("./LOGS/")

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
# import pydotplus
from sklearn import tree, metrics, model_selection, preprocessing
from IPython.display import Image, display
#from utils import plot_decision

# Data Import and preparation

In [2]:
xlsx = pd.ExcelFile('./data.xlsx')
df = pd.read_excel(xlsx, 'training data')
dataset1= df.copy()

inputs = dataset1.copy()

target = inputs.pop('Y')

In [3]:
df['class_label'], _ = pd.factorize(df['Y'])
df['Y'].unique()

array(['bubble', 'slug', 'churn', 'annular'], dtype=object)

In [4]:
# select features
y = df['class_label'] #Dependent feature
X = df[['Voltage', 'SD']] #Independent features (subset)

In [5]:
# split data randomly into 70% training and 30% test
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, 
                                                                    test_size=0.3, random_state=0)

# Training model

In [6]:
# train the decision tree
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

# Testing the model

In [7]:
y_pred = dtree.predict(X_test)

In [8]:
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Accuracy: 0.91


In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 7  1  0  0]
 [ 0 20  0  0]
 [ 0  3  7  0]
 [ 0  0  0  6]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.93         8
           1       0.83      1.00      0.91        20
           2       1.00      0.70      0.82        10
           3       1.00      1.00      1.00         6

    accuracy                           0.91        44
   macro avg       0.96      0.89      0.92        44
weighted avg       0.92      0.91      0.91        44



In [ ]:
tree.plot_tree(dtree)

# Lets analyze the tree

In [ ]:
os.environ['PATH'] = os.environ['PATH']+';'+os.environ['CONDA_PREFIX']+r"\Library\bin\graphviz"

In [ ]:
dot_data = tree.export_graphviz(dtree, out_file=None, filled=True, rounded=True,
                                feature_names=['sepal.length', 'sepal.width'],  
                                class_names=['setosa', 'versicolor', 'virginica'])
graph =  .graph_from_dot_data(dot_data)  
display(Image(graph.create_png()))

# Advantages of decision trees

# Disadvantages of decision trees

Tips on practical use
Decision trees tend to overfit on data with a large number of features. Check ratio of samples to number of features

Consider performing dimensionality reduction (PCA, ICA, or Feature selection) beforehand

Visualise your tree as you are training by using the export function. Use max_depth=3 as an initial tree depth.

Use max_depth to control the size of the tree to prevent overfitting.

Tune min_samples_split or min_samples_leaf to control the number of samples at a leaf node.

Balance your dataset before training to prevent the tree from being biased toward the classes that are dominant.

By sampling an equal number of samples from each class

By normalizing the sum of the sample weights (sample_weight) for each class to the same value.