In [2]:
import warnings
warnings.filterwarnings('ignore')

from IPython.display import Image
# Image("C:\\Users\\User\\Desktop\\XGB.png")



In [3]:
# Importing needed packages
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
#Importing various models to compare
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [5]:
import pandas as pd
# pd.DataFrame(mydata).shape

In [10]:
xlsx = pd.ExcelFile('./data.xlsx')
df = pd.read_excel(xlsx, 'training data')
dataset1= df.copy()

inputs = dataset1.copy()

target = inputs.pop('Y')

In [11]:
# split data into train and test sets
seed = 1
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.20, random_state=seed)

In [12]:
# the test data

xlsx1 = pd.ExcelFile('./data.xlsx')
df2 = pd.read_excel(xlsx1, 'test data')
dataset2= df2.copy()


X_test2 = dataset2.copy()

y_test2 = inputs2.pop('Y')


NameError: name 'inputs2' is not defined

In [13]:
#Running various models
models = []
models.append(('LogisticRegression', LogisticRegression()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('SVM', SVC()))
models.append(('XGB',XGBClassifier(eta=0.01,gamma=10))) #eta = 0.01,gamma = 10

import time
from sklearn.metrics import classification_report, confusion_matrix

# evaluate each model in turn
results = []
names = []
scoring = 'accuracy'

for name, model in models:
    start_time = time.time()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
#     predictions = [round(value) for value in y_pred]
    predictions= y_pred
    print(confusion_matrix(y_test, y_pred))


    # evaluate predictions
    accuracy = accuracy_score(y_test, predictions)
    print("Accuracy: %.2f%%" % (accuracy * 100.0),name)
    print("--- %s seconds ---" % (time.time() - start_time))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    
    #evalute for external data
    y_pred2 = model.predict(X_test2)
    accuracy2 = accuracy_score(y_test2, y_pred2)
    print("for test data")
    print("Accuracy on test data: %.2f%%" % (accuracy2 * 100.0),name)
    
    
    


[[ 3  0  0  0]
 [ 0  4  0  0]
 [ 0  0  5  0]
 [ 0  1  1 15]]
Accuracy: 93.10% LogisticRegression
--- 1.5393431186676025 seconds ---
[[ 3  0  0  0]
 [ 0  4  0  0]
 [ 0  0  5  0]
 [ 0  1  1 15]]
              precision    recall  f1-score   support

     annular       1.00      1.00      1.00         3
      bubble       0.80      1.00      0.89         4
       churn       0.83      1.00      0.91         5
        slug       1.00      0.88      0.94        17

    accuracy                           0.93        29
   macro avg       0.91      0.97      0.93        29
weighted avg       0.94      0.93      0.93        29



ValueError: could not convert string to float: 'bubble'

In [ ]:
Test

In [ ]:
xlsx1 = pd.ExcelFile('./data.xlsx')
df2 = pd.read_excel(xlsx1, 'test data')
dataset2= df2.copy()


inputs2 = dataset2.copy()

targetx = inputs2.pop('Y')



# print('train samples:', len(inputs))
print('test samples', len(inputs))


In [ ]:
for name, model in models:
 

    y_predx = model.predict(inputs2)
#     predictions = [round(value) for value in y_pred]
    predictionsx= y_predx
    print(confusion_matrix(targetx, y_predx))


    # evaluate predictions
    accuracy = accuracy_score(targetx, predictionsx)
    print("Accuracy: %.2f%%" % (accuracy * 100.0),name)
    print("--- %s seconds ---" % (time.time() - start_time))
    print(confusion_matrix(targetx, y_predx))
    print(classification_report(targetx, y_predx))
    